import { useEffect,useState } from 'react'
import { supabase } from '../lib/supabase'
import { statusClass, today } from '../lib/utils'

export default function Deliveries(){
  const [rows,setRows]=useState<any[]>([])
  const [orders,setOrders]=useState<any[]>([])
  const [f,setF]=useState({service_order_id:'',team:'',vehicle:'',route:'',address:'',installation_date:today(),installation_time:'',status:'Agendado',notes:''})
  useEffect(()=>{load()},[])
  async function load(){const [i,o]=await Promise.all([supabase.from('installations').select('*,service_orders(os_number,service)').order('installation_date',{ascending:false}),supabase.from('service_orders').select('id,os_number,service').order('created_at',{ascending:false})]);setRows(i.data||[]);setOrders(o.data||[])}
  async function save(e:React.FormEvent){e.preventDefault();await supabase.from('installations').insert({...f,service_order_id:f.service_order_id||null,installation_time:f.installation_time||null});setF({service_order_id:'',team:'',vehicle:'',route:'',address:'',installation_date:today(),installation_time:'',status:'Agendado',notes:''});load()}
  async function update(id:string,status:string){await supabase.from('installations').update({status}).eq('id',id);load()}
  return <div><h1 className="text-4xl font-black">Entrega / Instalação</h1><form onSubmit={save} className="card my-6 grid gap-3 md:grid-cols-4"><select className="input" value={f.service_order_id} onChange={e=>setF({...f,service_order_id:e.target.value})}><option value="">Sem OS</option>{orders.map(o=><option key={o.id} value={o.id}>{o.os_number} - {o.service}</option>)}</select><input className="input" placeholder="Equipe" value={f.team} onChange={e=>setF({...f,team:e.target.value})}/><input className="input" placeholder="Veículo" value={f.vehicle} onChange={e=>setF({...f,vehicle:e.target.value})}/><input className="input" placeholder="Rota" value={f.route} onChange={e=>setF({...f,route:e.target.value})}/><input className="input md:col-span-2" placeholder="Endereço" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><input className="input" type="date" value={f.installation_date} onChange={e=>setF({...f,installation_date:e.target.value})}/><input className="input" type="time" value={f.installation_time} onChange={e=>setF({...f,installation_time:e.target.value})}/><select className="input" value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Agendado</option><option>Em rota</option><option>Concluído</option><option>Reagendado</option><option>Cancelado</option></select><input className="input md:col-span-2" placeholder="Observações" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><button className="btn-gold">Agendar</button></form><div className="card table-wrap"><table><thead><tr><th>OS</th><th>Equipe</th><th>Veículo</th><th>Rota</th><th>Data</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.service_orders?.os_number}<br/><small>{r.service_orders?.service}</small></td><td>{r.team}</td><td>{r.vehicle}</td><td>{r.route}</td><td>{r.installation_date}</td><td><select className={`input ${statusClass(r.status)}`} value={r.status} onChange={e=>update(r.id,e.target.value)}><option>Agendado</option><option>Em rota</option><option>Concluído</option><option>Reagendado</option><option>Cancelado</option></select></td></tr>)}</tbody></table></div></div>
}
