import { useEffect, useMemo, useState } from 'react'
import jsPDF from 'jspdf'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { brNumber, money } from '../lib/utils'

const n=(v:any)=>brNumber(v)
export default function RetailInventory(){
 const [rows,setRows]=useState<any[]>([]), [q,setQ]=useState(''), [edit,setEdit]=useState<any>(null), [msg,setMsg]=useState('')
 const empty={name:'',product_code:'',barcode:'',stock:'0',cost_price:'0',sale_price:'0'}
 const [form,setForm]=useState<any>(empty)
 useEffect(()=>{load()},[])
 async function load(){const {data,error}=await supabase.from('retail_products').select('*').order('name');if(error)setMsg(error.message);setRows(data||[])}
 const filtered=useMemo(()=>rows.filter(r=>`${r.name} ${r.product_code||''} ${r.barcode||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q])
 async function save(e:React.FormEvent){e.preventDefault();setMsg('');const {data:u}=await supabase.auth.getUser();const payload={name:form.name,product_code:form.product_code||null,barcode:form.barcode||null,stock:n(form.stock),cost_price:n(form.cost_price),sale_price:n(form.sale_price),active:true,updated_at:new Date().toISOString(),user_id:u.user?.id};const r=edit?await supabase.from('retail_products').update(payload).eq('id',edit.id):await supabase.from('retail_products').insert(payload);if(r.error){setMsg(r.error.message);return}setEdit(null);setForm(empty);load()}
 async function del(id:string){if(!confirm('Excluir este produto?'))return;await supabase.from('retail_products').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);load()}
 function inventoryPdf(){const pdf=new jsPDF('p','mm','a4');const inv=filtered;const invested=inv.reduce((a,r)=>a+n(r.stock)*n(r.cost_price),0);const sale=inv.reduce((a,r)=>a+n(r.stock)*n(r.sale_price),0);const profit=sale-invested;let y=16;pdf.setFont('helvetica','bold');pdf.setFontSize(16);pdf.text('INVENTÁRIO - ESTOQUE VAREJO',10,y);y+=8;pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.text(`Gerado em ${new Date().toLocaleString('pt-BR')}`,10,y);y+=8;pdf.text(`Produtos: ${inv.length} | Investido: ${money(invested)} | Valor de venda: ${money(sale)} | Lucro potencial: ${money(profit)} | Margem: ${sale?Math.round(profit/sale*100):0}%`,10,y);y+=8;pdf.line(10,y,200,y);y+=6;pdf.setFontSize(8);pdf.setFont('helvetica','bold');pdf.text('Produto',10,y);pdf.text('Código',72,y);pdf.text('Barras',103,y);pdf.text('Qtd',140,y);pdf.text('Compra',153,y);pdf.text('Venda',175,y);y+=5;pdf.setFont('helvetica','normal');inv.forEach(r=>{if(y>282){pdf.addPage();y=16}pdf.text(String(r.name).slice(0,30),10,y);pdf.text(String(r.product_code||'-').slice(0,12),72,y);pdf.text(String(r.barcode||'-').slice(0,15),103,y);pdf.text(String(r.stock),140,y);pdf.text(money(n(r.cost_price)),153,y);pdf.text(money(n(r.sale_price)),175,y);y+=6});pdf.save(`inventario-varejo-${new Date().toISOString().slice(0,10)}.pdf`)}
 return <div className="page-fade"><header className="mb-5 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-4xl font-black">Estoque Varejo</h1><p className="text-zinc-400">Produtos físicos separados do estoque de comunicação visual.</p></div><div className="flex gap-2"><Link className="btn" to="/pdv-varejo">Ir para PDV</Link><button className="btn-gold" onClick={inventoryPdf}>PDF Inventário</button></div></header>{msg&&<div className="mb-4 rounded-xl bg-red-950/40 p-3 text-red-200">{msg}</div>}<form onSubmit={save} className="card mb-5 grid gap-3 md:grid-cols-6"><input className="input" placeholder="Nome do produto" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Código do produto" value={form.product_code} onChange={e=>setForm({...form,product_code:e.target.value})}/><input className="input" placeholder="Código de barras" value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/><input className="input" type="number" placeholder="Quantidade" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input className="input" placeholder="Valor de compra" value={form.cost_price} onChange={e=>setForm({...form,cost_price:e.target.value})}/><input className="input" placeholder="Valor de venda" value={form.sale_price} onChange={e=>setForm({...form,sale_price:e.target.value})}/><button className="btn-gold md:col-span-6">{edit?'Salvar alteração':'Cadastrar produto'}</button></form><div className="card"><div className="mb-4"><input className="input" placeholder="Pesquisar por nome, código ou código de barras..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Código</th><th>Barras</th><th>Qtd</th><th>Compra</th><th>Venda</th><th>Margem</th><th>Ações</th></tr></thead><tbody>{filtered.map(r=>{const margin=n(r.sale_price)-n(r.cost_price);return <tr key={r.id}><td>{r.name}</td><td>{r.product_code||'-'}</td><td>{r.barcode||'-'}</td><td className={n(r.stock)<=0?'text-red-300':''}>{r.stock}</td><td>{money(n(r.cost_price))}</td><td>{money(n(r.sale_price))}</td><td>{money(margin)}</td><td className="flex gap-2"><button className="btn" onClick={()=>{setEdit(r);setForm({...r,stock:String(r.stock),cost_price:String(r.cost_price),sale_price:String(r.sale_price)})}}>Editar</button><button className="btn-red" onClick={()=>del(r.id)}>Excluir</button></td></tr>})}{!filtered.length&&<tr><td colSpan={8} className="text-zinc-500">Nenhum produto encontrado.</td></tr>}</tbody></table></div></div></div>
}
