import { useEffect, useMemo, useState } from 'react'
import jsPDF from 'jspdf'
import { supabase } from '../lib/supabase'
import { money } from '../lib/utils'
export default function RetailFinance(){
 const [rows,setRows]=useState<any[]>([]),[period,setPeriod]=useState(new Date().toISOString().slice(0,7)),[msg,setMsg]=useState('')
 useEffect(()=>{load()},[period])
 async function load(){const start=`${period}-01`;const [y,m]=period.split('-').map(Number);const end=new Date(y,m,0).toISOString().slice(0,10);const {data,error}=await supabase.from('retail_sales').select('*,retail_sale_items(*)').gte('created_at',`${start}T00:00:00`).lte('created_at',`${end}T23:59:59`).order('created_at',{ascending:false});if(error)setMsg(error.message);setRows(data||[])}
 const total=useMemo(()=>rows.reduce((a,r)=>a+Number(r.total||0),0),[rows]), profit=useMemo(()=>rows.reduce((a,r)=>a+Number(r.profit||0),0),[rows])
 function pdf(){const p=new jsPDF('p','mm','a4');let y=16;p.setFontSize(16);p.setFont('helvetica','bold');p.text('FINANCEIRO VAREJO',10,y);y+=7;p.setFontSize(9);p.setFont('helvetica','normal');p.text(`Período: ${period} | Vendas: ${rows.length} | Total: ${money(total)} | Lucro: ${money(profit)}`,10,y);y+=8;p.line(10,y,200,y);y+=6;p.setFont('helvetica','bold');p.text('Data/Hora',10,y);p.text('Venda',48,y);p.text('Pagamento',90,y);p.text('Total',145,y);y+=6;p.setFont('helvetica','normal');rows.forEach(r=>{if(y>280){p.addPage();y=16}p.text(new Date(r.created_at).toLocaleString('pt-BR').slice(0,16),10,y);p.text(String(r.sale_number||r.id).slice(0,18),48,y);p.text(String(r.payment_method||'-'),90,y);p.text(money(Number(r.total||0)),145,y);y+=5;(r.retail_sale_items||[]).forEach((i:any)=>{if(y>280){p.addPage();y=16}p.setFontSize(7);p.text(`  ${i.product_name} | qtd ${i.quantity} | ${money(Number(i.unit_price||0))}`,12,y);p.setFontSize(9);y+=4})});p.save(`financeiro-varejo-${period}.pdf`)}
 return <div><header className="mb-5 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-4xl font-black">Financeiro Varejo</h1><p className="text-zinc-400">Histórico das vendas de produtos de varejo.</p></div><div className="flex gap-2"><input type="month" className="input" value={period} onChange={e=>setPeriod(e.target.value)}/><button className="btn-gold" onClick={pdf}>Baixar PDF</button></div></header>{msg&&<div className="mb-4 rounded-xl bg-red-950/40 p-3 text-red-200">{msg}</div>}<section className="mb-5 grid gap-4 md:grid-cols-3"><article className="metric-card"><small>Vendas</small><h2 className="text-3xl font-black">{rows.length}</h2></article><article className="metric-card"><small>Faturamento varejo</small><h2 className="text-3xl font-black">{money(total)}</h2></article><article className="metric-card"><small>Lucro bruto</small><h2 className="text-3xl font-black">{money(profit)}</h2></article></section><div className="card table-wrap"><table><thead><tr><th>Data/Hora</th><th>Venda</th><th>Produtos</th><th>Quantidade</th><th>Pagamento</th><th>Valor</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('pt-BR')}</td><td>{r.sale_number||r.id.slice(0,8)}</td><td>{(r.retail_sale_items||[]).map((i:any)=><div key={i.id}>{i.product_name}</div>)}</td><td>{(r.retail_sale_items||[]).reduce((a:number,i:any)=>a+Number(i.quantity||0),0)}</td><td>{r.payment_method}</td><td>{money(Number(r.total||0))}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="text-zinc-500">Nenhuma venda no período.</td></tr>}</tbody></table></div></div>
}
